### ISSUE TITLE
keyTransformations usage

### ISSUE THREAD

**Issue by clyang82** [brancz/locutus#33]
From this file - https://github.com/brancz/locutus/blob/main/example/jsonnet-with-crd-as-config/config.yaml, we can see that we can use `keyTransformations` to transfer the key from `observatorium/grafana-main` to `observatorium/main` (observatorium is a namespace) so that it can trigger sync in https://github.com/brancz/locutus/blob/main/trigger/resource/resource.go#L212:L223. in other word, if you delete the grafana deployment, it will trigger sync to recreate the grafana deployment.

Can you guide me how to write the regex to trigger sync in https://github.com/observatorium/operator if I modify the configuration to watch deployment/statefulset/etc.
```
mainResource: obs
resources:
- name: obs
  kind: Observatorium
  apiVersion: core.observatorium.io/v1alpha1
- name: deployment
  kind: Deployment
  apiVersion: apps/v1
  labelSelector:
    matchLabels:
      app.kubernetes.io/part-of: observatorium
```
the observatorium CR is defined by the customer. It can be `observatorium-xyz` or others. so we cannot hardcode it in regex. the deployments I want to watch are 
```
observatorium-xyz-loki-distributor
observatorium-xyz-loki-query-frontend
observatorium-xyz-observatorium-api
observatorium-xyz-thanos-query
observatorium-xyz-thanos-query-frontend
observatorium-xyz-thanos-receive-controller
```
